### ISSUE TITLE
Whitenoise requirement?

### ISSUE THREAD

**Issue by jfmatth** [openshift/django-ex#39]
I noticed that whitenoise is in the requirements.txt file, and it in the wsgy.py file, but in reading the docs from whitenoise, it doesn't seem to match the django setup.

Is this correct?

**Comment by bparees** [comment]
Can you elaborate on what doesn't match up?

**Comment by jfmatth** [comment]
HI @bparees, thanks for the quick response.

According to the latest [whitenoise documentation](http://whitenoise.evans.io/en/stable/#quickstart-for-django-apps), we only need to add some middleware classes, and we are done, but I don't see those in the current settings.py file.  Also, there is no mention of having to call the WSGI server in the way we do.

I'm not sure if this is me or did someone check-in incomplete code, i don't know.

**Comment by bparees** [comment]
@jfmatth I see..if you want to make a pull i'll be happy to give it a spin.

**Comment by jfmatth** [comment]
Ok

**Comment by jfmatth** [comment]
@bparees I see the reason for the difference.  v3.x eliminates the need to modify the wsgi.py file, and just has you install middleware.

However, pip doesn't show 3.x as being available yet.

The only thing that would need changing in this repo is the version number of whitenoise to more current (v2.x).  I'll wait until 3.x is out to try and test an PR for you.

thanks for responding, keep up the great work!
