### ISSUE TITLE
Remove debug-toolbar from requirements.txt

### ISSUE THREAD

**Issue by jfmatth** [openshift/django-ex#41]
Why do we have the debug-toolbar in this repo?  

Could we move it to a note in the readme.MD instead?

Just a thought.

**Comment by bparees** [comment]
@rhcarvalho guessing you wrote this originally though i can't remember for sure..

**Comment by rhcarvalho** [comment]
This repo is really just an example.
The `django-debug-toolbar` is included because it helps debugging database connectivity among other things.

You don't have to have it in your own app.

**Comment by PI-Victor** [comment]
![screenshot from 2016-06-08 13-13-17](https://cloud.githubusercontent.com/assets/6294120/15892610/e9d36034-2d7a-11e6-96fe-508e5ccba98d.png)
the debug-toolbar displays the toolbar on the right used for debugging, as @rhcarvalho pointed this is an example and the toolbar helps you debug. Users can remove it from their final app, but it should stay in this example for users to see how it works.
