### ISSUE TITLE
Static folder

### ISSUE THREAD

**Issue by general03** [openshift/django-ex#48]
I tried to configure my static folder without success.
In the [setting file](https://github.com/openshift/django-ex/blob/master/project/settings.py) you have `STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') `but I don't find this folder on the repo

Someone can help me to configure my static folder ?

**Comment by bparees** [comment]
@rhcarvalho or @grahamdumpleton can you help here?

**Comment by PI-Victor** [comment]
and the link: https://docs.djangoproject.com/en/1.8/howto/static-files/

**Comment by general03** [comment]
Thanks @PI-Victor but you can imagine that I already done that.
My project works fine in local.
I tried several configurations and you can find more informations on my post : http://stackoverflow.com/questions/37845189/static-files-on-openshift-with-django
Thanks

**Comment by rhcarvalho** [comment]
Hi @general03, looking at your SO post, I think you're working with OpenShift v2, where you have cartridges and so on (current OpenShift Online offering).
This example repository is meant for use with OpenShift v3. Doesn't mean you get no help :)

When you run Django in production (debug=False), you need to handle serving static files by some other means.

- One way to do it is to setup a HTTP server like httpd or nginx.
- Or use a pure-Python solution like this repo is configured to use [WhiteNoise](http://whitenoise.evans.io/en/stable/).

Looking at the [implementation for the Python Cartridge](https://github.com/openshift/origin-server/blob/f10c29be426012edfa204dc5b405007a678de6d9/cartridges/openshift-origin-cartridge-python/usr/versions/shared/etc/conf.d/openshift.conf.erb#L13-L22), there's indeed an option to place files in `$OPENSHIFT_REPO_DIR/wsgi/static`:

```
<% #Backward compatibilty with wsgi/static/ directory
  if $SAFE!=2 && (File.directory?("#{ENV['OPENSHIFT_REPO_DIR']}wsgi/static") || File.symlink?("#{ENV['OPENSHIFT_REPO_DIR']}wsgi/static"))
    %><%= "Alias /static #{ENV['OPENSHIFT_REPO_DIR']}wsgi/static" %><%
  end
%>
```

So I suspect if you drop your static files in `wsgi/static` in your project repository it should work.

Definitely there must be some official documentation for that, @bparees any pointers?

**Comment by bparees** [comment]
@rhcarvalho good catch.  I can't seem to dig up any useful v2 python docs at the moment, but maybe @dinhxuanvu has a pointer.

**Comment by dinhxuanvu** [comment]
It doesn't look like we have an official document for this unfortunately or at least I couldn't find it anywhere. However, @rhcarvalho comment is correct regarding where to put static files `$OPENSHIFT_REPO_DIR/wsgi/static`. So his advice is the way to go.

Also, I found this post that looks useful. Please take a look: [StackOverflow](http://stackoverflow.com/questions/25912675/openshift-python-2-7-and-static-files-with-htaccess)

Thanks.

**Comment by jfmatth** [comment]
If you need a v2 version for django, try mine :)

https://github.com/jfmatth/openshift-django

**Comment by dinhxuanvu** [comment]
We do have a Django example for V2 which is [https://github.com/openshift/django-example](Django)

**Comment by dinhxuanvu** [comment]
@jfmatth Sorry pal :D... I couldn't resist stealing your thunder :P...

**Comment by jfmatth** [comment]
No worries, it's all free open source anyway, that's the way we do it.

But if ur at summit today, you can buy me a drink :)

**Comment by dinhxuanvu** [comment]
Haha. Sorry, I'm not at the Summit this year but next year when Summit is back in Boston, I owe you one :D.

**Comment by general03** [comment]
In the wsgi.py I have to have
```
sys.path.append(os .path.join(os.environ['OPENSHIFT_REPO_DIR']))
os.environ['DJANGO_SETTINGS_MODULE' ] = 'project.settings.app'
```
and in my settings.py
```
STATIC_ROOT = os.path.join(os.getenv('OPENSHIFT_REPO_DIR'), 'wsgi/static', )
STATIC_URL = '/static/'
```
And the filesystem of my website
```
repo
 project
  ...
 wsgi
  static
 wsgi.py
```

**Comment by jfmatth** [comment]
You should checkout my repo, those changes aren't required :).

good luck
