### ISSUE TITLE
Enable compression and caching

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/django-ex#52]
WhiteNoise recommends enabling compression and caching:
http://whitenoise.evans.io/en/stable/django.html#add-compression-and-caching-support

We could test that it works and enable it.

**Comment by jfmatth** [comment]
let me have a look see and what I can find.

**Comment by jfmatth** [comment]
interesting, looks like it affects the collectstatic command in that it creates unique files with different timestamps for cache.

**Comment by rhcarvalho** [comment]
Fixed by #53.
