### ISSUE TITLE
Log python

### ISSUE THREAD

**Issue by general03** [openshift/django-ex#54]
I tried to debug my app but I don't find python log with
`rhc tail -a project`
Or when I got to /var/lib/openshift/id/app-root/logs/python.log file I don't find more log than displayed at screen

How can I see all my python output console ?

**Comment by bparees** [comment]
@dinhxuanvu appears to be a v2 user.

**Comment by jfmatth** [comment]
@general03 

Hi, just to be clear, you're posting in a Openshift v3 issues django project, and your question is around an openshift v2 issue.  The django repo for v2 is https://github.com/openshift/django-example.

That being said, what logs are you looking for specifically in Openshift v2?  The python log should only show exceptions being handled, and application logging would go where you specify in your log settings.

**Comment by general03** [comment]
You're right @jfmatth it's a Openshift v2 issue. Can you move this issue in the right section ?

I don't use special log settings for my project

**Comment by jfmatth** [comment]
I don't have that ability, only red hat.

I would add logging, then you can see it in the logs that you manage

**Comment by jfmatth** [comment]
Feel free to checkout my settings file for logging info and how i do it

https://github.com/jfmatth/aim-openshift/blob/master/mysite/settings.py

**Comment by jfmatth** [comment]
i think we can close this now.

**Comment by dinhxuanvu** [comment]
@jfmatth Thanks for all the help. Appreciate it. :D
