### ISSUE TITLE
can't deploy on openshift

### ISSUE THREAD

**Issue by PI-Victor** [openshift/django-ex#57]
@bparees is this supposed to be empty?
https://github.com/openshift/django-ex/blob/master/openshift/templates/django-postgresql.json#L305

my deployment fails on openshift with imagePullBackOff and something like 

```
E0831 14:49:01.123388    1727 pod_workers.go:183] Error syncing pod e158c98e-6f78-11e6-
ada1-68f728fac2c0, skipping: failed to "StartContainer" for "postgresql" with ErrImagePull: 
"couldn't parse image reference \" \": invalid reference format"
```

**Comment by jhadvig** [comment]
@PI-Victor that shouldn't cause the issue... when you check https://github.com/openshift/rails-ex/blob/master/openshift/templates/rails-postgresql.json#L178 it's got empty value as well

**Comment by PI-Victor** [comment]
@jhadvig thanks for the help man. it was actually a namespace issue on my project, was using project `demo` instead of `openshift`
closing.
