### ISSUE TITLE
Why is APP_CONFIG defined in the template?

### ISSUE THREAD

**Issue by jfmatth** [openshift/django-ex#62]
I just spent 2hrs figuring out why my app_config values in my .s2i/environment setup didn't work, and it turns out that the template has a blank APP_CONFIG variable.

Is this there for a reason?  It seems to collide with the .s2i documentation, or rather it's spirit.

**Comment by bparees** [comment]
I think we were just trying to make it easier for people deploying the template to populate the value instead of having to provide an environment file.

**Comment by jfmatth** [comment]
Ben, thanks for the quick response.

I agree that would be great, but it just seems to conflict with the .s2i docs, etc.  At least it did for me.

Seems like it would be easier to tell them to add it and not put it in the template?

Just frustrated I guess :)
