### ISSUE TITLE
Can't connect to service with dashes in name

### ISSUE THREAD

**Issue by ghyde** [openshift/django-ex#77]
When the environment variable `DATABASE_SERVICE_NAME` contains dashes, `database.py` doesn't convert the dashes (`-`) into underscores (`_`) ([code][1]). This causes Django to fail to connect to the database.

For example, if my Openshift service is named `foo-1`, the corresponding environment variables are `FOO_1_SERVICE_HOST` and `FOO_1_SERVICE_PORT`. However, `database.py` tries to get the environment variables `FOO-1_SERVICE_HOST` and `FOO-1_SERVICE_PORT` ([code][2]), which aren't defined environment variables. Thus, `HOST` and `PORT` are set to `None`.

[1]: https://github.com/openshift/django-ex/blob/31f1455e3bf51ac0a9bcf51c2b69b0f13a2b585b/project/database.py#L14
[2]: https://github.com/openshift/django-ex/blob/31f1455e3bf51ac0a9bcf51c2b69b0f13a2b585b/project/database.py#L27

**Comment by bparees** [comment]
lgtm
